config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get 'auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get 'logout', to: 'sessions#destroy'

  resources :games, only: [:index, :show] do
    collection do
      post :refresh
    end

    member do
      post :sync
      get :upload_rankings
      post :update_rankings
      post :link_players
    end

    resources :ranking_profiles, only: [:index]
  end

  resource :info, only: [:show]

  resources :leagues, only: [:index, :show] do
    collection do
      post :refresh
      get :currently_refreshing
    end

    member do
      post :sync
      get :weekly
      get :players
      get :draft_board
      get :playoffs
      get :parity
      get :charts
    end
  end
end

app/models/league.rb
class League < ActiveRecord::Base
  include Syncable

  belongs_to :game
  has_many :teams
  has_many :draft_picks, autosave: true
  has_many :matchups, dependent: :destroy
  has_many :matchup_teams, through: :matchups
  has_many :finished_matchup_teams, ->(league){ where("status = 'postevent'") }, through: :matchups, source: "matchup_teams"
  has_and_belongs_to_many :users

  default_scope { order(start_date: :desc) }

  scope :unsynced, ->{ where(sync_finished_at: nil) }
  scope :interesting_draft, -> {
    joins(:draft_picks)
      .where.not(sync_finished_at: nil)
      .group("leagues.id")
      .having("count(leagues.id) > 0")
      .order(Arel.sql("RANDOM()"))
  }
  scope :interesting_season, -> {
    joins(:matchups)
      .where.not(sync_finished_at: nil)
      .where(start_week: 1)
      .group("leagues.id")
      .having("count(leagues.id) > 0")
      .order(Arel.sql("RANDOM()"))
  }
  scope :active, -> { where(game_id: Game.by_season.first(2)) }

  validates :name,
            :game,
            :yahoo_league_key,
            :yahoo_league_id, presence: true

  def assign_auction_picks
    picks = draft_picks.sort_by(&:cost)
    num_picks = picks.size
    picks.each.with_object({ count: 0, pick: num_picks, last_cost: nil}) do |draft_pick, info|
      info[:pick] = num_picks - info[:count] unless info[:last_cost] == draft_pick.cost
      info[:count] = info[:count] + 1
      info[:last_cost] = draft_pick.cost

      draft_pick.auction_pick = info[:pick]
    end
  end

  def past_leagues
    league = self
    result = []
    while league
      league = league.last_league
      result << league
    end
    result.compact
  end

  def last_league
    renew && self.class.find_by(yahoo_league_key: renew.split("_").join(".l."))
  end

  def weeks_in_a_season
    playoff_start_week - 1
  end

  def weeks_remaining
    playoff_start_week - current_week
  end

  def complete?
    teams.any? && sync_finished_at?
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :find_league, only: [:show, :weekly, :players, :draft_board, :playoffs, :parity, :charts]
  before_action :ensure_synced, only: [:weekly, :players, :draft_board, :playoffs, :parity, :charts]

  rescue_from Pundit::NotAuthorizedError, with: :please_log_in

  def index
    authorize :league, :index?
    @leagues = current_user.leagues.active
  end

  def refresh
    if current_user.currently_syncing?
      authorize :league, :index?
      redirect_to currently_refreshing_leagues_path
    else
      authorize :league, :refresh?

      YahooService.new(current_user).sync_leagues([Game.most_recent])
      # Game.all.each do |game|
      #   YahooService.new(current_user).sync_leagues(game)
      # end
      current_user.leagues.active.each do |league|
        YahooService.new(current_user).sync_league(league)
      end

      redirect_to leagues_path, notice: "Refreshed leagues"
    end
  end

  def currently_refreshing
    authorize :league, :index?
    redirect_to leagues_path if !current_user.currently_syncing?
  end

  def show
    authorize @league, :show?
  end

  def weekly
    authorize @league, :show?

    @week = (params[:week].presence || (@league.current_week - 1)).to_i
    @matchups = @league.matchups.where(week: @week)
    @matchup_stats = InterestingStatsService.by_matchup(@matchups)
    @team_stats = InterestingStatsService.by_team(@matchups.map(&:matchup_teams).flatten)
  end

  def players
    authorize @league, :show?
  end

  def sync
    league = current_user.leagues.find(params[:id])
    authorize league, :sync?
    YahooService.new(current_user).sync_league(league)

    redirect_to league_path(league), notice: "Synced league"
  end

  def draft_board
    authorize @league, :show?

    @ranking_type = params[:ranking] || case @league.points_per_reception
                                          when 1 then "ecr_ppr"
                                          when 0 then "ecr_standard"
                                          when 0.5 then "ecr_half_ppr"
                                          else "ecr_standard"
                                        end

    @teams =
      @league
        .draft_picks
        .order(auction_pick: :asc, pick: :asc)
        .each
        .with_object({}) do |draft_pick, acc|
          acc[draft_pick.team] ||= []

          info = case @ranking_type
            when "yahoo_adp"; draft_pick.yahoo_info
            when "ecr_standard"; draft_pick.ecr_standard_info
            when "ecr_ppr"; draft_pick.ecr_ppr_info
            when "ecr_half_ppr"; draft_pick.ecr_half_ppr_info
            when "position"; draft_pick.position_info
            end

          acc[draft_pick.team] << info
        end
  end

  def playoffs
    authorize @league, :show?

    @matchups = @league.matchups
    @teams = @league.teams
  end

  def parity
    authorize @league, :show?

    @matchups = @league.matchups
    @teams = @league.teams
  end

  def charts
    authorize @league, :show?

    @matchups = @league.matchups
    @teams = @league.teams
  end

  protected

  def find_league
    @league = League.find(params[:id])
  end

  def ensure_synced
    if !@league.complete?
      redirect_to league_path(@league), status: 302, notice: "Please sync this league"
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  def ranking_class(ranking_type, info)
    return "position-#{info.position.downcase}" if ranking_type == "position"
    case rank = info.vs_pick
    when 13..24
      "good-4"
    when 7..12
      "good-3"
    when 4..6
      "good-2"
    when 1..3
      "good-1"
    when 0
      "even"
    when -3..-1
      "bad-1"
    when -6..-4
      "bad-2"
    when -12..-7
      "bad-3"
    when -24..-13
      "bad-4"
    else
      if !rank
        "no-rank"
      elsif rank >= 25
        "good-5"
      elsif rank <= -25
        "bad-5"
      end
    end
  end
end

app/views/leagues/_draft_board_ad.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Draft board -->
<ins class="adsbygoogle"
     style="display:inline-block;width:320px;height:50px"
     data-ad-client="ca-pub-1367839244485068"
     data-ad-slot="2857517437"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/leagues/_navigation.html.haml
- content_for :outside_container do
  %nav.sub-nav.navbar.navbar-default.navbar-static-top(role="navigation")
    .container-fluid
      .navbar-header
        %a{class: "navbar-brand", href: league_path(@league)} #{@league.name} (#{@league.start_date.year})

      %p.navbar-text.pull-left
        - if @league.sync_finished_at
          Last synced #{time_ago_in_words(@league.sync_finished_at)} ago.
      - if policy(@league).sync?
        = link_to "Sync this league with Yahoo", sync_league_path(@league), method: :post, class: "btn btn-info navbar-btn pull-left", data: { disable_with: "Syncing..." }

.row
  .col-md-8
    %ul.nav.nav-pills
      %li{class: current_page?(controller: 'leagues', action: 'show') && "active"}= link_to "League Stats", league_path(@league)
      %li{class: current_page?(controller: 'leagues', action: 'weekly') && "active"}= link_to "Weekly Stats", weekly_league_path(@league)
      %li{class: current_page?(controller: 'leagues', action: 'charts') && "active"}= link_to "Charts", charts_league_path(@league)
      %li{class: current_page?(controller: 'leagues', action: 'draft_board') && "active"}= link_to "Post Draft Visualization Board", draft_board_league_path(@league)
      %li{class: current_page?(controller: 'leagues', action: 'playoffs') && "active"}= link_to "Playoff and Record Scenarios", playoffs_league_path(@league)
      %li{class: current_page?(controller: 'leagues', action: 'parity') && "active"}= link_to "Parity", parity_league_path(@league)
      - if !current_user
        %li= link_to "Get this for your league", root_path, class: "btn-danger"

app/views/leagues/charts.html.haml
- load_javascript_class "LeagueChartsPage", matchups: @matchups, teams: @teams, weeks: [@league.weeks_in_a_season, @league.current_week - 1].min

= render "leagues/navigation"

.page-header
  %h2
    Charts

= week_1_alert

#charts
  %p
    Calculating records...

app/views/leagues/currently_refreshing.html.haml
- content_for :head do
  %META{"http-equiv" => "refresh", content: "7;URL=#{currently_refreshing_leagues_path}"}

.container
  %br
  %br
  %br
  %p
    We are currently syncing your league. This page will refresh in a few seconds.
    = link_to "Click here if it does not.", currently_refreshing_leagues_path

app/views/leagues/draft_board.html.haml
- content_for :title, "Rosterbater - Draft Visualization of #{@league.name}"
- load_javascript_class "DraftBoardPage"

= render "leagues/navigation"

.page-header
  %h2 Post Draft Visualization Board

.btn-group.btn-group-justified(role="group")
  - if !current_user
    = link_to "Get your own draft visualized", root_path, class: "btn btn-danger"
  - ["Yahoo ADP", "ECR Standard", "ECR Half PPR", "ECR PPR", "Position"].each do |ranking_label|
    - ranking_param = ranking_label.downcase.split(" ").join("_")
    - prefix = ranking_label == "Position" ? "by" : "vs."
    - if @ranking_type == ranking_param
      %span.btn.btn-default.btn-primary.disabled
        = prefix
        = ranking_label
    - else
      = link_to "#{prefix} #{ranking_label}", draft_board_league_path(@league, ranking: ranking_param), class: "btn btn-primary"

%p This is a visualization of your draft. The colors represent the difference between where a player was picked, vs their ranking. Click the buttons above to compare draft picks against Yahoo's Average Draft Pick, or to #{link_to "Expert Consensus Rankings", "http://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php"} in either PPR or standard. For example, If Jamaal Charles was picked 3rd overall in your league but was ranked second, it would show up light green for being a late pick. Green picks are late picks against the ranking, where purple picks are reaches for players too early according to the ranking.

- if @league.is_auction_draft?
  %p
    Note: This is an
    %strong auction draft.
    The picks are shown as if they were picked in order of their cost.

.draft-board.colors-colorblind-safe
  %div.legend
    %div.color-schemes
      Color Schemes:
      %a.selected(href="#" data-color-scheme="colorblind-safe") [Colorblind safe]
      %a(href="#" data-color-scheme="red-green") [Red-Green]
    %div
      %span.good-5 25+
      %span.good-4 13-24
      %span.good-3 7-12
      %span.good-2 4-6
      %span.good-1 1-3
      %span.even Even
      %span.bad-1 1-3
      %span.bad-2 4-6
      %span.bad-3 7-12
      %span.bad-4 13-24
      %span.bad-5 25+
      %span.no-rank NA

  %table
    %thead
      %tr
        %th.round-number #
        - @teams.each do |(team, _)|
          %th= team.name
    %tbody
      - if !@teams.empty?
        - @teams.first.last.size.times do |i|
          %tr
            %td.round-number= i + 1
            - @teams.each do |(_, pick_infos)|
              - info = pick_infos[i]
              %td{class: ranking_class(@ranking_type, info)}
                %div
                  = info.name
                %div
                  = info.actual_pick
                  - if @league.is_auction_draft?
                    ($#{info.cost})

                  - if info.rank_value
                    vs
                    = info.rank_value
                %div
                  #{info.team_abbr} - #{info.position}
        - if @league.is_auction_draft?
          %tr
            %td t
            - @teams.each do |(team, pick_infos)|
              %td #{pick_infos.map(&:cost).sum}

%br
%br

app/views/leagues/index.html.haml
.container
  %h3 Your leagues

  - if policy(:league).refresh?
    = link_to "Sync your leagues with Yahoo", refresh_leagues_path, method: :post, class: "btn btn-primary btn-lg", data: { disable_with: "Syncing..." }

  - if current_user.sync_finished_at
    %p Last synced #{time_ago_in_words(current_user.sync_finished_at)} ago.

  - if @leagues.empty?
    No leagues present. Please sync your leagues with Yahoo.
  - else
    %table.table
      %thead
        %tr
          %th(width="33%") Name
          %th Year
          %th Number of teams
          %th Current Week
          %th Start Date
          %th End Date
      %tbody
        - @leagues.each do |league|
          %tr
            %td
              = link_to "Go", league_path(league), class: "btn btn-primary btn-lg"
              = link_to league.name, league_path(league)
            %td
              = league.start_date.try(:year)
            %td
              = league.num_teams
            %td
              = league.current_week
            %td
              = league.start_date
            %td
              = league.end_date

app/views/leagues/parity.html.haml
- load_javascript_class "LeagueParityPage", matchups: @matchups, teams: @teams, workerPath: asset_path("parity_worker.js")

= render "leagues/navigation"

.page-header
  %h2
    Parity
    %small AKA, the Circle of Suck.

.well
  Team A beat Team B, who beat Team C... who beat Team A.

= week_1_alert

#parity
  %p Calculating Parity...
#parity-message

app/views/leagues/playoffs.html.haml
- load_javascript_class "LeaguePlayoffsPage", matchups: @matchups, teams: @teams, weeks: @league.weeks_in_a_season

= render "leagues/navigation"

.page-header
  %h2
    Playoff and Record Scenarios
    %small #{@league.weeks_remaining} games remaining. #{@league.num_playoff_teams} teams in playoffs.

.well
  The grid below marks all possible records for a given team. Change the matchup outcomes below to see how it affects possible outcomes.

= week_1_alert

#playoffs-outcomes
  %p
    Calculating records...

.page-header
  %h2
    Matchups
    %small Select the winners

#playoffs-matchups
  %p
    Calculating matchups...

app/views/leagues/show.html.haml
- load_javascript_class "LeagueShowPage"

= render "leagues/navigation"

.page-header
  %h2
    Sortable League Stats
- if !@league.complete?
  %p No teams present. Please sync this league with Yahoo.
  - if policy(@league).sync?
    %p
      = link_to "Sync this league with Yahoo", sync_league_path(@league), method: :post, class: "btn btn-info", data: { disable_with: "Syncing..." }
  - else
    %p Please refresh in a few minutes to sync.
- else
  - team_attrs = %w(waiver_priority faab_balance number_of_moves number_of_trades has_clinched_playoffs points_for points_against rank wins losses ties)
  - stat_attrs = %w(mean std_dev)
  %table#league-teams
    %thead
      %tr
        %th(width="33%") Name
        - team_attrs.each do |attr|
          %th= attr.humanize
        - stat_attrs.each do |attr|
          %th= attr.humanize
    %tbody
      - @league.teams.by_rank.each do |team|
        %tr
          %td
            - if current_user && team.managers.map(&:yahoo_guid).include?(current_user.yahoo_uid)
              %strong= team.name
            - else
              = team.name
          - team_attrs.each do |attr|
            %td= team.public_send(attr)
          - stat_attrs.each do |attr|
            %td= team.stats.public_send(attr).round

- if !@league.matchups.empty?
  .page-header
    %h4
      Matchups
      %small (sortable)

  %table#league-matchup-teams
    %thead
      %tr
        %th(width="33%") Name
        %th Week
        %th Opponent
        %th Points
        %th Projected Points
        %th Points - Projected
    %tbody
      - @league.finished_matchup_teams.each do |matchup_team|
        %tr
          %td= matchup_team.team.name
          %td= matchup_team.matchup.week
          %td= matchup_team.opponent_matchup_team.team.name
          %td= matchup_team.points
          %td= matchup_team.projected_points
          %td= matchup_team.points - matchup_team.projected_points

%hr
%ul
  %li #{@league.matchups.count} Matchups
  %li #{@league.matchup_teams.count} Team records
  %li #{@league.finished_matchup_teams.count} Finished team records
  - %w(scoring_type current_week start_week end_week playoff_start_week start_date end_date trade_end_date points_per_reception).each do |attr|
    %li
      #{attr.humanize}: #{@league.public_send(attr)}

%h4 Past seasons:
%ul
  - @league.past_leagues.each do |league|
    %li
      #{league.name} (#{league.start_date.year})

app/views/leagues/weekly.html.haml
= render "leagues/navigation"

%ul.pagination
  - (@league.start_week..@league.current_week).each do |week|
    %li{class: ("active" if (week == @week))}
      = link_to "Week #{week}", weekly_league_path(week: week)

.page-header
  %h2
    Weekly Stats for week #{@week}
- @matchups.each do |matchup|
  %ul.list-group
    %li.list-group-item.active
      = matchup.matchup_teams.map(&:team).map(&:name).join(" vs ")
    - @matchup_stats.select{|stat| stat.matchup_id == matchup.id}.each do |stat|
      %li.list-group-item
        Matchup:
        - if stat.importance == :high
          Highest
        - if stat.importance == :low
          Lowest
        = stat.label
        = stat.value
    - matchup.matchup_teams.map(&:team).each do |team|
      - @team_stats.select{|stat| stat.team_id == team.id}.each do |stat|
        %li.list-group-item
          #{team.name}:
          - if stat.importance == :high
            Highest
          - if stat.importance == :low
            Lowest
          = stat.label
          = stat.value