config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get 'auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get 'logout', to: 'sessions#destroy'

  resources :games, only: [:index, :show] do
    collection do
      post :refresh
    end

    member do
      post :sync
      get :upload_rankings
      post :update_rankings
      post :link_players
    end

    resources :ranking_profiles, only: [:index]
  end

  resource :info, only: [:show]

  resources :leagues, only: [:index, :show] do
    collection do
      post :refresh
      get :currently_refreshing
    end

    member do
      post :sync
      get :weekly
      get :players
      get :draft_board
      get :playoffs
      get :parity
      get :charts
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    authorize :welcome, :index?
    @draft_leagues = League.interesting_draft.limit(10)
    @season_leagues = League.interesting_season.limit(10).to_a
    League.connection.clear_query_cache
    @season_leagues2 = League.interesting_season.limit(10).to_a
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
- content_for :outside_container do
  .jumbotron
    .container
      %h1 Rosterbater
      %h2 Taking data from Yahoo Fantasy Football leagues and creating visualizations with it.

      - if current_user
        %p
          %a.btn.btn-primary.btn-lg{href: leagues_path} Look at your leagues now »
      - else
        %p
          By signing into yahoo, you will allow us to automatically import your league's information. We are only given read permissions, and cannot make changes to your account, league, team, or roster.
        %p
          %a.btn.btn-primary.btn-lg{href: "/auth/yahoo"} Sign in with yahoo »

.container
  .row
    .col-md-4
      %h2 Sortable in season stats
      %p
        I often need help cherry-picking interesting data from my league for weekly emails and trash talk, so I created some sortable tables.

      %h3 Example in season stats
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th Name
            %th Number of teams
        %tbody
          - @season_leagues.each do |league|
            %tr
              %td
                = link_to league.name, league_path(league)
              %td
                = league.num_teams

    .col-md-4
      %h2 Playoff/Team win scenarios
      %p
        I wanted to see what the playoff implications of certain wins and losses were, so I made a tool to show possible outcomes

      %h3 Example playoff scenarios
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th Name
            %th Number of teams
        %tbody
          - @season_leagues2.each do |league|
            %tr
              %td
                = link_to league.name, playoffs_league_path(league)
              %td
                = league.num_teams


    .col-md-4
      %h2 Post Draft Visualization Board
      %p
        This is a simple tool that gives a visualization of your draft after automatically importing your league's draft results. Colors represent the difference between where a player was picked vs their ranking, to help see which picks were good deals and which were reaches. You can compare draft picks against Yahoo's Average Draft Pick, or to #{link_to "Expert Consensus Rankings", "http://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php"} in either PPR or standard formats.

      %h3 Example Post Draft Visualization Boards
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th Name
            %th Number of teams
        %tbody
          - @draft_leagues.each do |league|
            %tr
              %td
                = link_to league.name, draft_board_league_path(league)
                - if league.is_auction_draft?
                  (auction)
              %td
                = league.num_teams