config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get 'auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get 'logout', to: 'sessions#destroy'

  resources :games, only: [:index, :show] do
    collection do
      post :refresh
    end

    member do
      post :sync
      get :upload_rankings
      post :update_rankings
      post :link_players
    end

    resources :ranking_profiles, only: [:index]
  end

  resource :info, only: [:show]

  resources :leagues, only: [:index, :show] do
    collection do
      post :refresh
      get :currently_refreshing
    end

    member do
      post :sync
      get :weekly
      get :players
      get :draft_board
      get :playoffs
      get :parity
      get :charts
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :ranking_profiles
  has_many :ranking_reports
  has_many :leagues

  scope :by_season, -> { order(season: :desc) }

  def self.most_recent
    by_season.first!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_path
  end

  def index
    authorize :game, :index?
    @games = Game.order(season: :desc)
  end

  def refresh
    authorize :game, :refresh?
    YahooService.new(current_user).sync_games

    redirect_to games_path, notice: "Refreshed games"
  end

  def sync
    game = Game.find(params[:id])
    authorize game, :sync?

    YahooService.new(current_user).sync_game(game)

    redirect_to games_path, notice: "Synced game"
  end

  def upload_rankings
    @game = Game.find(params[:id])
    authorize @game, :sync?
  end

  def update_rankings
    @game = Game.find(params[:id])
    authorize @game, :sync?

    EcrRankingsService.new.tap do |service|
      if standard = params[:rankings][:standard]
        service.sync_standard_draft_rankings(@game, standard.read)
      end
      if ppr = params[:rankings][:ppr]
        service.sync_ppr_draft_rankings(@game, ppr.read)
      end
      if half_ppr = params[:rankings][:half_ppr]
        service.sync_half_ppr_draft_rankings(@game, half_ppr.read)
      end
    end

    redirect_to games_path, notice: "Synced rankings"
  end

  def link_players
    game = Game.find(params[:id])
    authorize game, :sync?

    game.ranking_profiles.unlinked.map(&:link)

    redirect_to games_path, notice: "Linked players"
  end
end

app/views/games/index.html.haml
%h3 Games
= link_to "Refresh", refresh_games_path, method: :post, class: "button small"

- if @games.empty?
  No games present. Please refresh.
- else
  %table.table
    %thead
      %tr
        %td(width="40%")
        %td Yahoo Game Key
        %td Yahoo Game ID
        %td Name
        %td Code
        %td Game Type
        %td Url
        %td Season
        %td Created At
        %td Updated At
    %tbody
      - @games.each do |game|
        %tr
          %td
            %ul.button-group
              %li= link_to "Sync Players", sync_game_path(game), method: :post, data: { disable_with: "Syncing..." }
              %li= link_to "Upload Ranking Report", upload_rankings_game_path(game)
              %li= link_to "Link Players", link_players_game_path(game), method: :post, data: { disable_with: "Syncing..." }
              %li= link_to "Ranking Profiles", game_ranking_profiles_path(game), class: "button tiny"
          %td= game.yahoo_game_key
          %td= game.yahoo_game_id
          %td= game.name
          %td= game.code
          %td= game.game_type
          %td= link_to "link", game.url
          %td= game.season
          %td= game.created_at
          %td= game.updated_at

app/views/games/upload_rankings.html.haml
%h3= @game.name
%h3= @game.season

= form_for :rankings, url: { action: :update_rankings }, method: :post do |f|
  = f.label :standard
  = f.file_field :standard
  %hr
  = f.label :ppr
  = f.file_field :ppr
  %hr
  = f.label :half_ppr
  = f.file_field :half_ppr
  %hr
  = f.submit