config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get 'auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get 'logout', to: 'sessions#destroy'

  resources :games, only: [:index, :show] do
    collection do
      post :refresh
    end

    member do
      post :sync
      get :upload_rankings
      post :update_rankings
      post :link_players
    end

    resources :ranking_profiles, only: [:index]
  end

  resource :info, only: [:show]

  resources :leagues, only: [:index, :show] do
    collection do
      post :refresh
      get :currently_refreshing
    end

    member do
      post :sync
      get :weekly
      get :players
      get :draft_board
      get :playoffs
      get :parity
      get :charts
    end
  end
end

app/views/layouts/_footer_ad.html.erb
<div class="alignleft">
<script type='text/javascript'>
 amzn_assoc_ad_type = 'banner';
 amzn_assoc_tracking_id = 'rb0133-20';
 amzn_assoc_marketplace = 'amazon';
 amzn_assoc_region = 'US';
 amzn_assoc_placement = 'assoc_banner_placement_default';
 amzn_assoc_linkid = '42GNZ5HAFUY65JFU';
 amzn_assoc_campaigns = 'sp815_930fbkickkoff';
 amzn_assoc_banner_type = 'category';
 amzn_assoc_isresponsive = 'true';
</script>
<script src='//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1'></script>
</div>

app/views/layouts/_footer_ad_2.html.erb
<script type="text/javascript"><!--
amazon_ad_tag = "rb0133-20"; amazon_ad_width = "728"; amazon_ad_height = "90";//--></script>
<script type="text/javascript" src="http://ir-na.amazon-adsystem.com/s/ads.js"></script>

app/views/layouts/_footer_ad_3.html.erb
<iframe src="http://rcm-na.amazon-adsystem.com/e/cm?t=rb0133-20&o=1&p=48&l=st1&mode=sporting&search=football&fc1=000000&lt1=_blank&lc1=3366FF&bg1=FFFFFF&f=ifr" marginwidth="0" marginheight="0" width="728" height="90" border="0" frameborder="0" style="border:none;" scrolling="no"></iframe>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-4379922-6', 'auto');
  ga('require', 'linkid', 'linkid.js');
  ga('set', 'pageGroup1', '<%= controller.controller_name %>.<%= controller.action_name %>')
  ga('send', 'pageview');

</script>

app/views/layouts/_messages.html.haml
- if flash.any?
  .row
    .col-md-12
      - flash.each do |name, msg|
        %div(class="alert alert-#{name.to_s == 'notice' ? 'success' : 'warning'}")
          %button(type="button" class="close" data-dismiss="alert")
            %span(aria-hidden="true") &times;
            %span(class="sr-only") Close
          = msg

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}

    %meta{property: "og:title", content: "Fantasy Football Visualizations"}
    %meta{property: "og:description", content: "Rosterbater is a simple tool that gives a visualization of your draft after automatically importing your league's draft results. Colors represent the difference between where a player was picked vs their ranking, to help see which picks were good deals and which were reaches. You can compare draft picks against Yahoo's Average Draft Pick, or to Expert Consensus Rankings in either PPR or standard formats."}
    %title= content_for?(:title) ? yield(:title) : "Rosterbater - Fantasy Football Visualizations"

    = yield(:head)

    = stylesheet_link_tag "application", media: "all"
    = favicon_link_tag 'favicon.ico'

    = csrf_meta_tags
  %body
    %nav.main-nav.navbar.navbar-inverse.navbar-static-top(role="navigation")
      .container-fluid
        .navbar-header
          %a(class="navbar-brand" href="/") Rosterbater

        %ul.nav.navbar-nav.navbar-right
          - if policy(:game).index?
            %li= link_to "Game Admin", games_path
          - if policy(:info).show?
            %li= link_to "Info", info_path
          - if current_user
            %li= link_to "My Leagues", leagues_path
            %li= link_to "Logout", logout_path
          - else
            %li
              %a{href: "/auth/yahoo"} Sign in with yahoo

    = yield :outside_container

    .container-fluid
      = render "layouts/messages"
      = yield

      %br
      %br
      %footer.footer
        %p &copy; Rosterbater #{Time.now.year} - #{link_to "See on Github", "https://github.com/phillc/rosterbater"}

    <script src="https://d3js.org/d3.v6.js"></script>
    = javascript_include_tag "application"
    = render "layouts/google_analytics"
    = yield :page_javascripts